In [1]:
pip install yfinance

Collecting yfinance
  Downloading yfinance-1.2.0-py2.py3-none-any.whl.metadata (6.1 kB)
Requirement already satisfied: pandas>=1.3.0 in c:\users\kaige\anaconda3\lib\site-packages (from yfinance) (2.1.4)
Requirement already satisfied: numpy>=1.16.5 in c:\users\kaige\anaconda3\lib\site-packages (from yfinance) (1.26.4)
Requirement already satisfied: requests>=2.31 in c:\users\kaige\anaconda3\lib\site-packages (from yfinance) (2.31.0)
Collecting multitasking>=0.0.7 (from yfinance)
  Using cached multitasking-0.0.12-py3-none-any.whl
Requirement already satisfied: platformdirs>=2.0.0 in c:\users\kaige\appdata\roaming\python\python311\site-packages (from yfinance) (4.3.7)
Requirement already satisfied: pytz>=2022.5 in c:\users\kaige\anaconda3\lib\site-packages (from yfinance) (2023.3.post1)
Collecting frozendict>=2.3.4 (from yfinance)
  Downloading frozendict-2.4.7-py3-none-any.whl.metadata (23 kB)
Collecting peewee>=3.16.2 (from yfinance)
  Downloading peewee-4.0.3-py3-none-any.whl.metadata (8.6 kB)
Requirement already satisfied: beautifulsoup4>=4.11.1 in c:\users\kaige\anaconda3\lib\site-packages (from yfinance) (4.12.2)
Collecting curl_cffi<0.14,>=0.7 (from yfinance)
  Downloading curl_cffi-0.13.0-cp39-abi3-win_amd64.whl.metadata (13 kB)
Requirement already satisfied: protobuf>=3.19.0 in c:\users\kaige\anaconda3\lib\site-packages (from yfinance) (5.29.5)
Collecting websockets>=13.0 (from yfinance)
  Downloading websockets-16.0-cp311-cp311-win_amd64.whl.metadata (7.0 kB)
Requirement already satisfied: soupsieve>1.2 in c:\users\kaige\anaconda3\lib\site-packages (from beautifulsoup4>=4.11.1->yfinance) (2.5)
Requirement already satisfied: cffi>=1.12.0 in c:\users\kaige\anaconda3\lib\site-packages (from curl_cffi<0.14,>=0.7->yfinance) (1.16.0)
Requirement already satisfied: certifi>=2024.2.2 in c:\users\kaige\anaconda3\lib\site-packages (from curl_cffi<0.14,>=0.7->yfinance) (2024.2.2)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\kaige\appdata\roaming\python\python311\site-packages (from pandas>=1.3.0->yfinance) (2.9.0.post0)
Requirement already satisfied: tzdata>=2022.1 in c:\users\kaige\anaconda3\lib\site-packages (from pandas>=1.3.0->yfinance) (2023.3)
Requirement already satisfied: charset-normalizer<4,>=2 in c:\users\kaige\anaconda3\lib\site-packages (from requests>=2.31->yfinance) (2.0.4)
Requirement already satisfied: idna<4,>=2.5 in c:\users\kaige\anaconda3\lib\site-packages (from requests>=2.31->yfinance) (3.4)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\users\kaige\anaconda3\lib\site-packages (from requests>=2.31->yfinance) (2.0.7)
Requirement already satisfied: pycparser in c:\users\kaige\anaconda3\lib\site-packages (from cffi>=1.12.0->curl_cffi<0.14,>=0.7->yfinance) (2.21)
Requirement already satisfied: six>=1.5 in c:\users\kaige\appdata\roaming\python\python311\site-packages (from python-dateutil>=2.8.2->pandas>=1.3.0->yfinance) (1.17.0)
Downloading yfinance-1.2.0-py2.py3-none-any.whl (130 kB)
   ---------------------------------------- 0.0/130.2 kB ? eta -:--:--
   ---------------------------------------- 130.2/130.2 kB 3.8 MB/s eta 0:00:00
Downloading curl_cffi-0.13.0-cp39-abi3-win_amd64.whl (1.6 MB)
   ---------------------------------------- 0.0/1.6 MB ? eta -:--:--
   ------ --------------------------------- 0.3/1.6 MB 5.7 MB/s eta 0:00:01
   ------------ --------------------------- 0.5/1.6 MB 5.1 MB/s eta 0:00:01
   ------------------- -------------------- 0.8/1.6 MB 5.4 MB/s eta 0:00:01
   --------------------------- ------------ 1.1/1.6 MB 5.8 MB/s eta 0:00:01
   ---------------------------------- ----- 1.4/1.6 MB 5.9 MB/s eta 0:00:01
   ---------------------------------------- 1.6/1.6 MB 6.0 MB/s eta 0:00:00
Downloading frozendict-2.4.7-py3-none-any.whl (16 kB)
Downloading peewee-4.0.3-py3-none-any.whl (144 kB)
   ---------------------------------------- 0.0/144.5 kB ? eta -:--:--
   ---------------------------------------- 144.5/144.5 kB 4.3 MB/s eta 0:00:00
Downloading websockets-16.0-cp311-cp311-win_amd64.whl (178 kB)
   ---------------------------------------- 0.0/178.7 kB ? eta -:--:--
   -------------------------------------- - 174.1/178.7 kB 5.3 MB/s eta 0:00:01
   ---------------------------------------- 178.7/178.7 kB 3.7 MB/s eta 0:00:00
Installing collected packages: peewee, multitasking, websockets, frozendict, curl_cffi, yfinance
Successfully installed curl_cffi-0.13.0 frozendict-2.4.7 multitasking-0.0.12 peewee-4.0.3 websockets-16.0 yfinance-1.2.0
Note: you may need to restart the kernel to use updated packages.

In [9]:
import yfinance
import pandas as pd
from sklearn.preprocessing import MinMaxScaler
import numpy as np

apple = yfinance.download("AAPL", start = "2016-03-01", end = "2026-03-01")
apple

[*********************100%***********************]  1 of 1 completed

Price            Close        High         Low        Open     Volume
Ticker            AAPL        AAPL        AAPL        AAPL       AAPL
Date
2016-03-01   22.768087   22.822442   22.063733   22.115824  201628400
2016-03-02   22.817905   22.849613   22.566512   22.763551  132678400
2016-03-03   22.987768   23.035329   22.749963   22.779407  147822800
2016-03-04   23.329758   23.497353   22.958330   23.184810  184220400
2016-03-07   23.071560   23.288981   22.865462   23.189329  143315600
...                ...         ...         ...         ...        ...
2026-02-23  266.179993  269.429993  263.380005  263.489990   37308200
2026-02-24  272.140015  274.890015  267.709991  267.859985   47014600
2026-02-25  274.230011  274.940002  271.049988  271.779999   33714300
2026-02-26  272.950012  276.109985  270.799988  274.950012   32345100
2026-02-27  264.179993  272.809998  262.890015  272.809998   72366500

[2514 rows x 5 columns]

In [4]:
apple["Close"]

Ticker            AAPL
Date
2016-03-01   22.768087
2016-03-02   22.817905
2016-03-03   22.987768
2016-03-04   23.329758
2016-03-07   23.071560
...                ...
2026-02-23  266.179993
2026-02-24  272.140015
2026-02-25  274.230011
2026-02-26  272.950012
2026-02-27  264.179993

[2514 rows x 1 columns]

In [10]:
minMax = MinMaxScaler(feature_range = (0, 1))
CloseMinMax = minMax.fit_transform(apple["Close"])
CloseMinMax

array([[0.00822827],
       [0.00841602],
       [0.0090562 ],
       ...,
       [0.95593372],
       [0.95110968],
       [0.91805738]])

In [30]:
features = []
target = []

for i in range(len(CloseMinMax)//60):
    #tempList = []
    start = i * 60
    end = start + 60
    features.append(CloseMinMax[start:end])
    target.append(CloseMinMax[end:end+1])


#len(features)
#print(features[0][0])
#print(target[1])
print(target)
print(CloseMinMax[120])
# 1 to 60, 2 to 61 ... for features
# 61, 62 ... for target

[array([[0.00796924]]), array([[0.01684223]]), array([[0.01415938]]), array([[0.03757609]]), array([[0.05663797]]), array([[0.05857484]]), array([[0.06568169]]), array([[0.07330393]]), array([[0.06872186]]), array([[0.0916483]]), array([[0.11369245]]), array([[0.05963762]]), array([[0.09949776]]), array([[0.10535003]]), array([[0.12158787]]), array([[0.17628578]]), array([[0.14532565]]), array([[0.23560469]]), array([[0.35169277]]), array([[0.37303229]]), array([[0.37047541]]), array([[0.38307644]]), array([[0.47373075]]), array([[0.47929267]]), array([[0.54513958]]), array([[0.49380135]]), array([[0.53473736]]), array([[0.49026243]]), array([[0.46371849]]), array([[0.53081986]]), array([[0.63645677]]), array([[0.58817476]]), array([[0.61467718]]), array([[0.55610273]]), array([[0.76889998]]), array([[0.79481605]]), array([[0.89023339]]), array([[0.76202616]]), array([[0.67764753]]), array([[0.81824851]]), array([[0.97209941]])]
[0.01684223]